; PlatformIO Project Configuration
; LOLIN32 (ESP32) + HC-SR04 + Buzzer

[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9
